import { RulePattern } from './types';

export const STYLE_RULES: RulePattern[] = [
  // Business Tone
  { regex: /\bhit me up\b/gi, exp: "Informal tone. Consider 'contact me' or 'reach out'.", rep: "contact me", type: 'style' },
  { regex: /\bgonna check it out\b/gi, exp: "Informal tone. Consider 'will review this'.", rep: "will review this", type: 'style' },
  { regex: /\blet me know asap\b/gi, exp: "Informal tone. Consider 'please advise at your earliest convenience'.", rep: "please advise at your earliest convenience", type: 'style' },
  { regex: /\bmy bad\b/gi, exp: "Informal phrase. Consider 'I apologize for the oversight'.", rep: "I apologize for the oversight", type: 'style' },
  { regex: /\bthanks a lot\b/gi, exp: "Consider a formal business closing like 'Thank you very much'.", rep: "Thank you very much", type: 'style' },
  { regex: /\bno problem\b/gi, exp: "In business context, consider 'You are welcome' or 'Happy to help'.", rep: "You are welcome", type: 'style' },
  { regex: /\bin a nutshell\b/gi, exp: "Informal phrase. Use 'in summary' or 'in brief'.", rep: "in summary", type: 'style' },
  { regex: /\bat the end of the day\b/gi, exp: "Cliche phrase. Consider 'ultimately'.", rep: "ultimately", type: 'style' },
  { regex: /\ba bunch of\b/gi, exp: "Informal quantifier. Use 'several' or 'a number of'.", rep: "several", type: 'style' },
  { regex: /\bmake sure that\b/gi, exp: "Consider using concise business term 'ensure that'.", rep: "ensure that", type: 'style' },
  { regex: /\bgive an update\b/gi, exp: "Consider using 'provide an update'.", rep: "provide an update", type: 'style' },
  { regex: /\btake a look at\b/gi, exp: "Consider using formal term 'review'.", rep: "review", type: 'style' },
  { regex: /\bfind out\b/gi, exp: "Consider using 'determine' or 'discover'.", rep: "determine", type: 'style' },
  { regex: /\bset up\b/gi, exp: "Consider using 'arrange' or 'establish'.", rep: "arrange", type: 'style' },

  // Jargon
  { regex: /\butilize(s|d|ing)?\b/gi, exp: "Wordy jargon. Consider using 'use'.", rep: "use", type: 'style' },
  { regex: /\bcognizant of\b/gi, exp: "Complex phrasing. Consider using 'aware of'.", rep: "aware of", type: 'style' },
  { regex: /\bcommence(s|d|ing)?\b/gi, exp: "Formal jargon. Consider using 'begin' or 'start'.", rep: "begin", type: 'style' },
  { regex: /\bterminate(s|d|ing)?\b/gi, exp: "Formal jargon. Consider using 'end' or 'stop'.", rep: "end", type: 'style' },
  { regex: /\bfacilitate(s|d|ing)?\b/gi, exp: "Vague jargon. Consider using 'help' or 'enable'.", rep: "help", type: 'style' },
  { regex: /\bsynergize\b/gi, exp: "Corporate jargon. Consider 'collaborate' or 'work together'.", rep: "collaborate", type: 'style' },

  // Phrasal Verbs -> Formal Alternatives
  { regex: /\bcall(ed|s)? off\b/gi, exp: "Informal phrasal verb. Consider formal verb 'cancel'.", rep: "cancel", type: 'style' },
  { regex: /\bput(s)? off\b/gi, exp: "Informal phrasal verb. Consider formal verb 'postpone' or 'delay'.", rep: "postpone", type: 'style' },
  { regex: /\bcarry (out|out)\b/gi, exp: "Informal phrasal verb. Consider formal verb 'execute' or 'conduct'.", rep: "execute", type: 'style' },
  { regex: /\blook(ed|s|ing)? into\b/gi, exp: "Informal phrasal verb. Consider formal verb 'investigate' or 'examine'.", rep: "investigate", type: 'style' },
  { regex: /\bbring(s)? up\b/gi, exp: "Informal phrasal verb. Consider formal verb 'mention' or 'raise'.", rep: "raise", type: 'style' },
  { regex: /\bcame up with\b/gi, exp: "Informal phrasal verb. Consider formal verb 'devised' or 'developed'.", rep: "devised", type: 'style' },
  { regex: /\bpoint(ed|s)? out\b/gi, exp: "Informal phrasal verb. Consider formal verb 'indicate' or 'highlight'.", rep: "indicate", type: 'style' },
  { regex: /\bwork(ed|s)? out\b/gi, exp: "Informal phrasal verb. Consider formal verb 'resolve' or 'calculate'.", rep: "resolve", type: 'style' },
  { regex: /\bfigure(d|s)? out\b/gi, exp: "Informal phrasal verb. Consider formal verb 'determine' or 'understand'.", rep: "determine", type: 'style' },
  { regex: /\bfill(ed|s)? out\b/gi, exp: "Informal phrasal verb. Consider formal verb 'complete'.", rep: "complete", type: 'style' },
  { regex: /\bget(ting)? rid of\b/gi, exp: "Informal phrasal verb. Consider formal verb 'eliminate' or 'remove'.", rep: "eliminate", type: 'style' },
  { regex: /\bgot rid of\b/gi, exp: "Informal phrasal verb. Consider formal verb 'eliminated' or 'removed'.", rep: "eliminated", type: 'style' },
  { regex: /\bturn(ed|s)? down\b/gi, exp: "Informal phrasal verb. Consider formal verb 'decline' or 'reject'.", rep: "decline", type: 'style' },
  { regex: /\bback(ed|s)? up\b/gi, exp: "Informal phrasal verb. Consider formal verb 'substantiate' or 'support'.", rep: "substantiate", type: 'style' },
  { regex: /\bbreak(s|ing)? down\b/gi, exp: "Informal phrasal verb. Consider formal verb 'analyze' or 'itemize'.", rep: "analyze", type: 'style' },
  { regex: /\bbroken down\b/gi, exp: "Informal phrasal verb. Consider formal verb 'analyzed' or 'itemized'.", rep: "analyzed", type: 'style' },

  // Wordiness & Redundancy Rules
  { regex: /\bat this point in time\b/gi, exp: "Consider simplifying to 'now'.", rep: "now", type: 'style' },
  { regex: /\bdue to the fact that\b/gi, exp: "Consider simplifying to 'because'.", rep: "because", type: 'style' },
  { regex: /\bin order to\b/gi, exp: "Consider simplifying to 'to'.", rep: "to", type: 'style' },
  { regex: /\bend result\b/gi, exp: "Redundant phrasing. Use 'result'.", rep: "result", type: 'style' },
  { regex: /\bbasic fundamentals\b/gi, exp: "Redundant phrasing. Use 'fundamentals'.", rep: "fundamentals", type: 'style' },
  { regex: /\bfuture plans\b/gi, exp: "Redundant phrasing. Use 'plans'.", rep: "plans", type: 'style' },
  { regex: /\babsolutely necessary\b/gi, exp: "Redundant phrasing. Use 'necessary'.", rep: "necessary", type: 'style' },
  { regex: /\brevert back\b/gi, exp: "Redundant phrasing. Use 'revert'.", rep: "revert", type: 'style' },
  { regex: /\bclose proximity\b/gi, exp: "Consider simplifying to 'near'.", rep: "near", type: 'style' },
  { regex: /\bfor the purpose of\b/gi, exp: "Consider simplifying to 'for' or 'to'.", rep: "to", type: 'style' },
  { regex: /\bactual fact\b/gi, exp: "Redundant phrasing. Use 'fact'.", rep: "fact", type: 'style' },
  { regex: /\badvance warning\b/gi, exp: "Redundant phrasing. Use 'warning'.", rep: "warning", type: 'style' },
  { regex: /\bempty space\b/gi, exp: "Redundant phrasing. Use 'space'.", rep: "space", type: 'style' },
  { regex: /\bfree gift\b/gi, exp: "Redundant phrasing. Use 'gift'.", rep: "gift", type: 'style' },
  { regex: /\bpast history\b/gi, exp: "Redundant phrasing. Use 'history'.", rep: "history", type: 'style' },
  { regex: /\bunexpected surprise\b/gi, exp: "Redundant phrasing. Use 'surprise'.", rep: "surprise", type: 'style' },
  { regex: /\badd an additional\b/gi, exp: "Redundant phrasing. Use 'add a'.", rep: "add a", type: 'style' },
  { regex: /\bask the question\b/gi, exp: "Redundant phrasing. Use 'ask'.", rep: "ask", type: 'style' },
  { regex: /\bbrief summary\b/gi, exp: "Redundant phrasing. Use 'summary'.", rep: "summary", type: 'style' },
  { regex: /\bcompletely finished\b/gi, exp: "Redundant phrasing. Use 'finished'.", rep: "finished", type: 'style' },
  { regex: /\bdepreciate in value\b/gi, exp: "Redundant phrasing. Use 'depreciate'.", rep: "depreciate", type: 'style' },
  { regex: /\bexact same\b/gi, exp: "Redundant phrasing. Use 'exact' or 'same'.", rep: "same", type: 'style' },
  { regex: /\bnew innovation\b/gi, exp: "Redundant phrasing. Use 'innovation'.", rep: "innovation", type: 'style' },
  { regex: /\bsum total\b/gi, exp: "Redundant phrasing. Use 'total'.", rep: "total", type: 'style' },
  { regex: /\bwhether or not\b/gi, exp: "Wordy phrasing. Often 'whether' is sufficient.", rep: "whether", type: 'style' }
];
